import { 
  LayoutDashboard, 
  Users, 
  Filter, 
  FileText, 
  Building2, 
  HelpCircle, 
  LogOut,
  Bell,
  Settings,
  TrendingUp,
  Cake,
  MoreVertical,
  Search,
  Plus,
  ChevronLeft,
  ChevronRight,
  UploadCloud,
  CheckCircle2,
  Phone,
  Mail,
  X,
  Check,
  Info
} from "lucide-react";

export const Icons = {
  Dashboard: LayoutDashboard,
  Leads: Users,
  Funnel: Filter,
  Contracts: FileText,
  FileText: FileText,
  Carriers: Building2,
  Building2: Building2,
  Filter: Filter,
  Support: HelpCircle,
  Logout: LogOut,
  Notifications: Bell,
  Settings: Settings,
  TrendingUp: TrendingUp,
  Cake: Cake,
  More: MoreVertical,
  Search: Search,
  Plus: Plus,
  ChevronLeft: ChevronLeft,
  ChevronRight: ChevronRight,
  Upload: UploadCloud,
  CheckCircle: CheckCircle2,
  Phone: Phone,
  Mail: Mail,
  X: X,
  Check: Check,
  Info: Info
};
